variable "project_id" {}
variable "project_name" {}
variable "vpc_name" {}
variable "billing_account" {}
variable "public_ip" {}
variable "default_region" {}
variable "ssh_user" {}
variable "ssh_publickey_path" {}
variable "vpn_shared_secret" {}
